###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun


#################
### AUTOSTART ###
#################

exec-once = waybar & swaync
exec-once = swww-daemon & hypridle
# Auto-close special workspace when focusing a normal window
exec-once = bash ~/.config/hypr/scripts/close_special.sh

# Set GTK theme to dark mode
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
env = GTK_THEME,Adwaita:dark
