###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun


#################
### AUTOSTART ###
#################

# System Apps
exec-once = waybar & swaync
exec-once = swww-daemon & hypridle

# Set Dark Mode
exec-once = gsettings set org.gnome.desktop.interface gtk-theme 'Adwaita-dark'
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
env = GTK_THEME,Adwaita:dark

# Scripts
exec-once = bash ~/.config/hypr/scripts/close_special.sh

# Apps
exec-once = google-chrome-stable --app-id=cinhimbnkkaeohfgghhklpknlkffjgod
